// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBll89FifkeAIcAdTwdp_Gj3xIjLz1nO-Q',
    appId: '1:1038186379046:web:45d2064436337a88bd33e7',
    messagingSenderId: '1038186379046',
    projectId: 'streakup-0001',
    authDomain: 'streakup-0001.firebaseapp.com',
    storageBucket: 'streakup-0001.firebasestorage.app',
    measurementId: 'G-FQW8Z0MHWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArjWkrEfn3_WSo6yCzWwbXRIdmzjxHim0',
    appId: '1:1038186379046:android:b8e872fda2710a06bd33e7',
    messagingSenderId: '1038186379046',
    projectId: 'streakup-0001',
    storageBucket: 'streakup-0001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXTKn3SGA4ViwwsB0WhlA75Rx_kONy9HE',
    appId: '1:1038186379046:ios:3a732670c7fecb4bbd33e7',
    messagingSenderId: '1038186379046',
    projectId: 'streakup-0001',
    storageBucket: 'streakup-0001.firebasestorage.app',
    iosBundleId: 'com.neubatu.streakup.streakup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXTKn3SGA4ViwwsB0WhlA75Rx_kONy9HE',
    appId: '1:1038186379046:ios:3a732670c7fecb4bbd33e7',
    messagingSenderId: '1038186379046',
    projectId: 'streakup-0001',
    storageBucket: 'streakup-0001.firebasestorage.app',
    iosBundleId: 'com.neubatu.streakup.streakup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBll89FifkeAIcAdTwdp_Gj3xIjLz1nO-Q',
    appId: '1:1038186379046:web:ad50fe3e4ebec0a9bd33e7',
    messagingSenderId: '1038186379046',
    projectId: 'streakup-0001',
    authDomain: 'streakup-0001.firebaseapp.com',
    storageBucket: 'streakup-0001.firebasestorage.app',
    measurementId: 'G-6BZN7PXHD9',
  );
}
